
export const sample_Items: any[] = [
  {
    id: "0",
    name: "GIGABYTE 8GB RTX4060Ti AERO OC GeForce VGA Graphic Card",
    price: 162,
    specification: [
      "GeForce RTX™ 4060 Ti (8GB)",
      "Core Clock",
      "2580 MHz (Reference Card: 2535 MHz)",
      "CUDA® Cores",
      "4352",
      "Memory Clock",
      "18 Gbps",
      "Memory Size",
      "8 GB",
      "Memory Type",
      "GDDR6",
      "Memory Bus",
      "128 bit",
      "Card Bus",
      "PCI-E 4.0",
      "Digital max resolution",
      "7680×4320",
      "Multi-view",
      "4",
      "Card size",
      "L=281 W=117 H=50 mm",
      "PCB Form",
      "ATX",
      "DirectX",
      "12 Ultimate",
      "OpenGL",
      "4.6",
      "500W",
      "Power Connectors",
      "8 pin*1",
      "Output",
      "DisplayPort 1.4a*2",
      "HDMI 2.1a*2",
    ],
    tags: ["Graphics Card", "gaming"],
    imageUrl: "assets/0.jpg",
  },
  {
    id: "1",
    name: "MSI 24GB RTX4090 GAMING X TRIO",
    price: 628,
    specification: [
      "Graphics Processing Unit NVIDIA® GeForce RTX™ 4090",
      "Interface PCI Express® Gen 4",
      "Core Clocks",
      "Extreme Performance: 2610 MHz (MSI",
      "Center) Boost: 2595 MHz (GAMING & SILENT",
      "Mode)",
      "CUDA® CORES 16384 Units",
      "Memory Speed 21 Gbps",
      "Memory 24GB GDDR6X",
      "Memory Bus 384-bit",
      "Output",
      "DisplayPort x 3 (v1.4a)",
      "HDMI™ x 1 (Supports 4K@120Hz HDR,",
      "8K@60Hz HDR, and Variable Refresh Rate as",
      "specified in HDMI 2.1a)",
      "HDCP Support Y",
      "Power consumption 450 W",
      "Power connectors 16-pin x 1",
      "Recommended PSU 850 W",
      "Card Dimension (mm) 337 x 140 x 77 mm",
      "Weight (Card / Package) 2170 g / 3093 g",
      "DirectX Version Support 12 Ultimate",
      "OpenGL Version Support 4.6",
      "Maximum Displays 4",
      "G-SYNC® technology Y",
      "Digital Maximum Resolution 7680×4320",
    ],
    tags: ["Graphics", "gaming"],
    imageUrl: "assets/1.jpg",
  },
  {
    id: "2",
    name: "Gigabyte Z490 AORUS ELITE AC Gaming Motherboard",
    price: 92,
    specification: [
      "1 x PCI Express x16 slot, running at x16 (PCIEX16)",
      "* For optimum performance,",
      "1 x PCI Express x16 slot,",
      "2 x PCI Express x1 slots",
      "2 x M.2 connectors ",
      "6 x SATA 6Gb/s connectors",
      "Support for RAID 0, RAID 1, RAID 5, and RAID 10",
    ],
    tags: ["Motherboard", "Gaming"],
    imageUrl: "assets/2.jpg",
  },
  {
    id: "3",
    name: "ASUS ROG CROSSHAIR VIII EXTREME AMD X570 EATX Gaming Motherboard DDR4",
    price: 235,
    specification: [
      "6 x SATA 6Gb/s ports",
      "Ethernet",
      "1 x Intel® 2.5Gb Ethernet",
      "1 x Marvell® 10Gb Ethernet",
      "1 x Intel® I225-V 2.5Gb Ethernet",
      "1 x Marvell® AQtion AQC113CS 10Gb Ethernet",
      "ASUS LANGuard",
      "Wireless & Bluetooth",
      "Wi-Fi 6E",
      "2×2 Wi-Fi 6E (802.11 a/b/g/n/ac/ax)",
      "Supports 2.4/5/6GHz frequency band*",
      "Bluetooth v5.2",
      "* WiFi 6E ",
    ],
    tags: ["Motherboard", "Gaming"],
    imageUrl: "assets/3.jpg",
  },
  {
    id: "4",
    name: "AMD Ryzen 5 7600X Processor",
    price: 99,
    specification: [
      "SKU CODE AW100100000593WOF",
      "Brand AMD",
      "Processor`s Type Desktop",
      "Processor Name",
      "AMD 5 Core Name",
      "ZEN 4 No# of Core`s 06-Core",
      "No# of Threads 12",
      "Operating Frequency Up to 5.3GHz",
      "i2 & i3 Cache 6MB",
      "Manufacturing Tech AMD",
      "PCI Express PCI Express 5.0",
      "Thermal Design Power Power Draw (TDP) 105W",
      "1 Year Warranty",
    ],
    tags: ["Processor"],
    imageUrl: "assets/4.jpg",
  },
  {
    id: "5",
    name: "ASUS 850W ROG Thor PSU",
    price: 68,
    specification: [
      "Intel Specification",
      "ATX12V",
      "16 x 15 x 8.6 Centimeter",
      "Protection Features",
      "OPP/OVP/UVP/SCP/OCP/OTP",
      "Hazardous Materials",
      "ROHS",
      "AC Input Range",
      "100-240Vac",
      "RGB Connector",
      "Aura Sync",
      "DC Output Voltage",
      "+3.3V +5V +12V -12V +5Vsb",
      "Maximum Load",
      "20A 20A 71A 0.3A 3A",
      "Total Output",
      "850W",
    ],
    tags: ["Power Supply", "Gaming"],
    imageUrl: "assets/0.jpg",
  },
  {
    id: "6",
    name: "GSKILL 32GB 4000MHz RAM TridentZ RGB (16GB x2) Kit",
    price: 79,
    specification: [
      "DDR4",
      "Capacity",
      "32GB (16GBx2)",
      "Multi-Channel Kit",
      "Dual Channel Kit",
      "Tested Speed",
      "4000MHz",
      "Tested Latency",
      "18-22-22-42",
      "Tested Voltage",
      "1.40V",
      "Registered/Unbuffered",
      "Unbuffered",
      "Error Checking",
      "Non-ECC",
      "SPD Speed",
      "2133MHz",
      "SPD Voltage",
      "1.20V",
    ],
    tags: ["RAM", "Gaming"],
    imageUrl: "assets/6.jpg",
  },
  {
    id: "7",
    name: "Kingston 16GB 3200MHz DDR4 Fury Beast RGB Desktop RAM Kit",
    price: 18,
    specification: [
      "EAN/UPC Code	740617319422",
      "Brand	Kingston",
      "Memory Capacity	16GB Kit (8GB x2)",
      "Module Quantity	2 Modules",
      "Speed (Data Rate)	3200MT/s (PC4-25600)",
      "Speed (Clock Rate)	1600Mhz",
      "Module Type	DIMM",
      "Error Check	Non-ECC",
      "Model/Series/Type	Fury Beast",
      "CAS Latency	CL16",
      "Form Factor	DDR4",
      "Rank	1R (Single Rank)",
      "Warranty	Lifetime",
      "Pins	288 Pin",
      "Colour	Black",
      "Operating Temperature	0°C to 70°C",
      "RGB Lighting	Yes",
      "DRAM Density	16Gbit",
      "Memory Voltage	1.35v",
      "Memory Depth	2G",
      "Product Condition	New",
      "Product Type/Family	RAM",
      "Packaging Type	Retail",
      "Data Width	X64",
      "Chip Organization	x8",
    ],
    tags: ["RAM", "Gaming"],
    imageUrl: "assets/7.jpg",
  },
];

export const sample_tags:any[]= [
  {name: 'All', count: 5},
  {name:'processor',count:4},
  {name:'motherboard',count:1}
]

export const sample_users: any[] = [
  {
    name: "Em Dy",
    email: "emdy@gmail.com",
    password: "12345",
    address: "Kuwait farwaniya",
    isAdmin: true,
  },
  {
    name: "Adam Smith",
    email: "asm@gmail.com",
    password: "12345",
    address: "China",
    isAdmin: false,
  },
];